import rs.uns.ac.ftn.Diplomski.model.Wine
import rs.uns.ac.ftn.Diplomski.model.Grape
import rs.uns.ac.ftn.Diplomski.model.drl.GrapeList
import rs.uns.ac.ftn.Diplomski.web.dto.GrapeListDTO
import rs.uns.ac.ftn.Diplomski.web.dto.GrapeDTO

import java.util.List;

rule "Missing Grenache for Chateauneuf-du-pape, Red rhone, Priorat, Provence rose"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "Red rhone" || wineName == "Priorat" || wineName == "Provence rose");
        $gl: GrapeList($grapeList: grapeLists);
        $grenache: Grape(grapeName == "Grenache")
        $missing: Grape(grapeName == "Grenache", $grapeList not contains $grenache);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($grenache));
end

rule "Missing Syrah for Chateauneuf-du-pape, Red rhone, Super tuscan, Priorat, Provence rose"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "Red rhone" || wineName == "Super tuscan"
                || wineName == "Priorat" || wineName == "Provence rose");
        $gl: GrapeList($grapeList: grapeLists);
        $syrah: Grape(grapeName == "Syrah")
        $missing: Grape(grapeName == "Syrah", $grapeList not contains $syrah);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($syrah));
end

rule "Missing Mourvedre for Chateauneuf-du-pape, Red rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "Red rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $mourvedre: Grape(grapeName == "Mourvedre")
        $missing: Grape(grapeName == "Mourvedre", $grapeList not contains $mourvedre);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($mourvedre));
end

rule "Missing Bourboulenc for Chateauneuf-du-pape, White rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "White rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $bourboulenc: Grape(grapeName == "Bourboulenc")
        $missing: Grape(grapeName == "Bourboulenc", $grapeList not contains $bourboulenc);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($bourboulenc));
end

rule "Missing Cinsault for Chateauneuf-du-pape, Provence rose"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "Provence rose");
        $gl: GrapeList($grapeList: grapeLists);
        $cinsault: Grape(grapeName == "Cinsault")
        $missing: Grape(grapeName == "Cinsault", $grapeList not contains $cinsault);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($cinsault));
end

rule "Missing Clairette Blanche for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $blanche: Grape(grapeName == "Clairette Blanche")
        $missing: Grape(grapeName == "Clairette Blanche", $grapeList not contains $blanche);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($blanche));
end

rule "Missing Counoise for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $counoise: Grape(grapeName == "Counoise")
        $missing: Grape(grapeName == "Counoise", $grapeList not contains $counoise);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($counoise));
end

rule "Missing Grenache Blanc for Chateauneuf-du-pape, White rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "White rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $blanc: Grape(grapeName == "Grenache Blanc")
        $missing: Grape(grapeName == "Grenache Blanc", $grapeList not contains $blanc);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($blanc));
end

rule "Missing Muscardin for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $muscardin: Grape(grapeName == "Muscardin")
        $missing: Grape(grapeName == "Muscardin", $grapeList not contains $muscardin);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($muscardin));
end

rule "Missing Picardan for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $picardan: Grape(grapeName == "Picardan")
        $missing: Grape(grapeName == "Picardan", $grapeList not contains $picardan);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($picardan));
end

rule "Missing Piquepoul Blanc for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $blanc: Grape(grapeName == "Piquepoul Blanc")
        $missing: Grape(grapeName == "Piquepoul Blanc", $grapeList not contains $blanc);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($blanc));
end

rule "Missing Roussanne for Chateauneuf-du-pape, White rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape" || wineName == "White rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $roussanne: Grape(grapeName == "Roussanne")
        $missing: Grape(grapeName == "Roussanne", $grapeList not contains $roussanne);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($roussanne));
end

rule "Missing Terret Noir for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $noir: Grape(grapeName == "Terret Noir")
        $missing: Grape(grapeName == "Terret Noir", $grapeList not contains $noir);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($noir));
end

rule "Missing Vaccarese for Chateauneuf-du-pape"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chateauneuf-du-pape");
        $gl: GrapeList($grapeList: grapeLists);
        $vaccarese: Grape(grapeName == "Vaccarese")
        $missing: Grape(grapeName == "Vaccarese", $grapeList not contains $vaccarese);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($vaccarese));
end

rule "Missing Merlot for Red bordeaux, Super tuscan, Priorat, Meritage"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bordeaux" || wineName == "Super tuscan" || wineName == "Priorat" || wineName == "Meritage");
        $gl: GrapeList($grapeList: grapeLists);
        $merlot: Grape(grapeName == "Merlot")
        $missing: Grape(grapeName == "Merlot", $grapeList not contains $merlot);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($merlot));
end

rule "Missing Cabernet Sauvignon for Red bordeaux, Chianti, Super tuscan, Priorat, Meritage"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bordeaux" || wineName == "Chianti" || wineName == "Super tuscan" || wineName == "Priorat"
                || wineName == "Meritage");
        $gl: GrapeList($grapeList: grapeLists);
        $cabernet: Grape(grapeName == "Cabernet Sauvignon")
        $missing: Grape(grapeName == "Cabernet Sauvignon", $grapeList not contains $cabernet);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($cabernet));
end

rule "Missing Cabernet Franc for Red bordeaux, Chianti, Super tuscan, Meritage"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bordeaux" || wineName == "Chianti" || wineName == "Super tuscan" || wineName == "Meritage");
        $gl: GrapeList($grapeList: grapeLists);
        $franc: Grape(grapeName == "Cabernet Franc")
        $missing: Grape(grapeName == "Cabernet Franc", $grapeList not contains $franc);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($franc));
end

rule "Missing Petit Verdot for Red bordeaux, Meritage"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bordeaux" || wineName == "Meritage");
        $gl: GrapeList($grapeList: grapeLists);
        $petit: Grape(grapeName == "Petit Verdot")
        $missing: Grape(grapeName == "Petit Verdot", $grapeList not contains $petit);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($petit));
end

rule "Missing Malbec for Red bordeaux, Meritage"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bordeaux" || wineName == "Meritage");
        $gl: GrapeList($grapeList: grapeLists);
        $malbec: Grape(grapeName == "Malbec")
        $missing: Grape(grapeName == "Malbec", $grapeList not contains $malbec);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($malbec));
end

rule "Missing Semillon for White bordeaux"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White bordeaux");
        $gl: GrapeList($grapeList: grapeLists);
        $semillon: Grape(grapeName == "Semillon")
        $missing: Grape(grapeName == "Semillon", $grapeList not contains $semillon);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($semillon));
end

rule "Missing Sauvignon Blanc for White bordeaux"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White bordeaux");
        $gl: GrapeList($grapeList: grapeLists);
        $blanc: Grape(grapeName == "Sauvignon Blanc")
        $missing: Grape(grapeName == "Sauvignon Blanc", $grapeList not contains $blanc);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($blanc));
end

rule "Missing Muscadelle for White bordeaux"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White bordeaux");
        $gl: GrapeList($grapeList: grapeLists);
        $muscadelle: Grape(grapeName == "Muscadelle")
        $missing: Grape(grapeName == "Muscadelle", $grapeList not contains $muscadelle);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($muscadelle));
end

rule "Missing Pinot Noir for Red bourgogne, Champagne"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bourgogne" || wineName == "Champagne");
        $gl: GrapeList($grapeList: grapeLists);
        $pinot: Grape(grapeName == "Pinot Noir")
        $missing: Grape(grapeName == "Pinot Noir", $grapeList not contains $pinot);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($pinot));
end

rule "Missing Gamay for Red bourgogne"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Red bourgogne");
        $gl: GrapeList($grapeList: grapeLists);
        $gamay: Grape(grapeName == "Gamay")
        $missing: Grape(grapeName == "Gamay", $grapeList not contains $gamay);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($gamay));
end

rule "Missing Chardonnay for White bourgogne, Soave, Champagne, Cava"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White bourgogne" || wineName == "Soave" || wineName == "Champagne" || wineName == "Cava");
        $gl: GrapeList($grapeList: grapeLists);
        $chardonnay: Grape(grapeName == "Chardonnay")
        $missing: Grape(grapeName == "Chardonnay", $grapeList not contains $chardonnay);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($chardonnay));
end

rule "Missing Aligote for White bourgogne"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White bourgogne");
        $gl: GrapeList($grapeList: grapeLists);
        $aligote: Grape(grapeName == "Aligote")
        $missing: Grape(grapeName == "Aligote", $grapeList not contains $aligote);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($aligote));
end

rule "Missing Marsanne for White rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $marsanne: Grape(grapeName == "Marsanne")
        $missing: Grape(grapeName == "Marsanne", $grapeList not contains $marsanne);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($marsanne));
end

rule "Missing Viognier for White rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $viognier: Grape(grapeName == "Viognier")
        $missing: Grape(grapeName == "Viognier", $grapeList not contains $viognier);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($viognier));
end

rule "Missing Clairette for White rhone"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rhone");
        $gl: GrapeList($grapeList: grapeLists);
        $clairette: Grape(grapeName == "Clairette")
        $missing: Grape(grapeName == "Clairette", $grapeList not contains $clairette);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($clairette));
end

rule "Missing Garganega for Soave"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Soave");
        $gl: GrapeList($grapeList: grapeLists);
        $garganega: Grape(grapeName == "Garganega")
        $missing: Grape(grapeName == "Garganega", $grapeList not contains $garganega);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($garganega));
end

rule "Missing Trebbiano for Soave"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Soave");
        $gl: GrapeList($grapeList: grapeLists);
        $trebbiano: Grape(grapeName == "Trebbiano")
        $missing: Grape(grapeName == "Trebbiano", $grapeList not contains $trebbiano);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($trebbiano));
end

rule "Missing Pinot Blanc for Soave"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Soave");
        $gl: GrapeList($grapeList: grapeLists);
        $pinot: Grape(grapeName == "Pinot Blanc")
        $missing: Grape(grapeName == "Pinot Blanc", $grapeList not contains $pinot);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($pinot));
end

rule "Missing Sangiovese for Chianti"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Chianti" || wineName == "Super tuscan");
        $gl: GrapeList($grapeList: grapeLists);
        $sangiovese: Grape(grapeName == "Sangiovese")
        $missing: Grape(grapeName == "Sangiovese", $grapeList not contains $sangiovese);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($sangiovese));
end

rule "Missing Corvina for Amarone della valpolicella"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Amarone della valpolicella");
        $gl: GrapeList($grapeList: grapeLists);
        $corvina: Grape(grapeName == "Corvina")
        $missing: Grape(grapeName == "Corvina", $grapeList not contains $corvina);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($corvina));
end

rule "Missing Molinara for Amarone della valpolicella"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Amarone della valpolicella");
        $gl: GrapeList($grapeList: grapeLists);
        $molinara: Grape(grapeName == "Molinara")
        $missing: Grape(grapeName == "Molinara", $grapeList not contains $molinara);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($molinara));
end

rule "Missing Rondinella for Amarone della valpolicella"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Amarone della valpolicella");
        $gl: GrapeList($grapeList: grapeLists);
        $rondinella: Grape(grapeName == "Rondinella")
        $missing: Grape(grapeName == "Rondinella", $grapeList not contains $rondinella);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($rondinella));
end

rule "Missing Tempranillo for Rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $tempranillo: Grape(grapeName == "Tempranillo")
        $missing: Grape(grapeName == "Tempranillo", $grapeList not contains $tempranillo);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($tempranillo));
end

rule "Missing Mazuelo for Rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $mazuelo: Grape(grapeName == "Mazuelo")
        $missing: Grape(grapeName == "Mazuelo", $grapeList not contains $mazuelo);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($mazuelo));
end

rule "Missing Gracino for Rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $gracino: Grape(grapeName == "Gracino")
        $missing: Grape(grapeName == "Gracino", $grapeList not contains $gracino);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($gracino));
end

rule "Missing Maturana Tinta for Rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $maturana: Grape(grapeName == "Maturana Tinta")
        $missing: Grape(grapeName == "Maturana Tinta", $grapeList not contains $maturana);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($maturana));
end

rule "Missing Viura for White rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $viura: Grape(grapeName == "Viura")
        $missing: Grape(grapeName == "Viura", $grapeList not contains $viura);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($viura));
end

rule "Missing Malvasia for White rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $malvasia: Grape(grapeName == "Malvasia")
        $missing: Grape(grapeName == "Malvasia", $grapeList not contains $malvasia);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($malvasia));
end

rule "Missing Verdejo for White rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $verdejo: Grape(grapeName == "Verdejo")
        $missing: Grape(grapeName == "Verdejo", $grapeList not contains $verdejo);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($verdejo));
end

rule "Missing Garnacha Blanca for White rioja"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "White rioja");
        $gl: GrapeList($grapeList: grapeLists);
        $blanca: Grape(grapeName == "Garnacha Blanca")
        $missing: Grape(grapeName == "Garnacha Blanca", $grapeList not contains $blanca);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($blanca));
end

rule "Missing Carignan for Priorat"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Priorat");
        $gl: GrapeList($grapeList: grapeLists);
        $carignan: Grape(grapeName == "Carignan")
        $missing: Grape(grapeName == "Carignan", $grapeList not contains $carignan);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($carignan));
end

rule "Missing Carmenere for Meritage"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Meritage");
        $gl: GrapeList($grapeList: grapeLists);
        $carmenere: Grape(grapeName == "Carmenere")
        $missing: Grape(grapeName == "Carmenere", $grapeList not contains $carmenere);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($carmenere));
end

rule "Missing Touriga Nacional for Port"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Port");
        $gl: GrapeList($grapeList: grapeLists);
        $touriga: Grape(grapeName == "Touriga Nacional")
        $missing: Grape(grapeName == "Touriga Nacional", $grapeList not contains $touriga);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($touriga));
end

rule "Missing Touriga Franca for Port"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Port");
        $gl: GrapeList($grapeList: grapeLists);
        $touriga: Grape(grapeName == "Touriga Franca")
        $missing: Grape(grapeName == "Touriga Franca", $grapeList not contains $touriga);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($touriga));
end

rule "Missing Tinta Roriz for Port"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Port");
        $gl: GrapeList($grapeList: grapeLists);
        $tinta: Grape(grapeName == "Tinta Roriz")
        $missing: Grape(grapeName == "Tinta Roriz", $grapeList not contains $tinta);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($tinta));
end

rule "Missing Tinto Cao for Port"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Port");
        $gl: GrapeList($grapeList: grapeLists);
        $tinto: Grape(grapeName == "Tinto Cao")
        $missing: Grape(grapeName == "Tinto Cao", $grapeList not contains $tinto);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($tinto));
end

rule "Missing Tinta Barroca for Port"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Port");
        $gl: GrapeList($grapeList: grapeLists);
        $tinta: Grape(grapeName == "Tinta Barroca")
        $missing: Grape(grapeName == "Tinta Barroca", $grapeList not contains $tinta);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($tinta));
end

rule "Missing Rolle for Provence rose"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Provence rose");
        $gl: GrapeList($grapeList: grapeLists);
        $rolle: Grape(grapeName == "Rolle")
        $missing: Grape(grapeName == "Rolle", $grapeList not contains $rolle);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($rolle));
end

rule "Missing Pinot Meunier for Champagne"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Champagne");
        $gl: GrapeList($grapeList: grapeLists);
        $pinot: Grape(grapeName == "Pinot Meunier")
        $missing: Grape(grapeName == "Pinot Meunier", $grapeList not contains $pinot);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($pinot));
end

rule "Missing Macabeo for Cava"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Cava");
        $gl: GrapeList($grapeList: grapeLists);
        $macabeo: Grape(grapeName == "Macabeo")
        $missing: Grape(grapeName == "Macabeo", $grapeList not contains $macabeo);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($macabeo));
end

rule "Missing Parellada for Cava"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Cava");
        $gl: GrapeList($grapeList: grapeLists);
        $parellada: Grape(grapeName == "Parellada")
        $missing: Grape(grapeName == "Parellada", $grapeList not contains $parellada);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($parellada));
end

rule "Missing Xarello for Cava"
    agenda-group "missing-grapes"
    when
        $glDTO: GrapeListDTO();
        $rb: Wine(wineName == "Cava");
        $gl: GrapeList($grapeList: grapeLists);
        $xarello: Grape(grapeName == "Xarello")
        $missing: Grape(grapeName == "Xarello", $grapeList not contains $xarello);
    then
        $glDTO.getGrapeDTOs().add(new GrapeDTO($xarello));
end