import rs.uns.ac.ftn.Diplomski.model.Wine
import rs.uns.ac.ftn.Diplomski.model.Grape
import rs.uns.ac.ftn.Diplomski.model.drl.GrapeList
import rs.uns.ac.ftn.Diplomski.service.WineService
import rs.uns.ac.ftn.Diplomski.web.dto.GrapeListDTO
import rs.uns.ac.ftn.Diplomski.web.dto.GrapeDTO
import rs.uns.ac.ftn.Diplomski.web.dto.PotentialWinesDTO
import rs.uns.ac.ftn.Diplomski.web.dto.MissingGrapesDTO
import rs.uns.ac.ftn.Diplomski.web.dto.WineDTO

import java.util.List;

// WINE TO BE POTENTIAL HAS TO HAVE AT LEAST ONE GRAPE

rule "Potential Chateauneuf-du-pape"
    agenda-group "potential-wines"
    salience 10
    when
        $cdp: Wine(wineName == "Chateauneuf-du-pape");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Grenache" || grapeName == "Syrah" || grapeName == "Mourvedre" || grapeName == "Vaccarese" ||
            grapeName == "Bourboulenc" || grapeName == "Cinsault" || grapeName == "Clairette Blanche" || grapeName == "Counoise"
            || grapeName == "Grenache Blanc" || grapeName == "Muscardin" || grapeName == "Picardan" || grapeName == "Piquepoul Blanc"
            || grapeName == "Roussanne" || grapeName == "Terret Noir")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($cdp);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end


rule "Potential Red Bordeaux"
    agenda-group "potential-wines"
    salience 10
    when
        $rb: Wine(wineName == "Red bordeaux");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Merlot" || grapeName == "Cabernet Sauvignon" || grapeName == "Cabernet Franc" ||
            grapeName == "Petit Verdot" || grapeName == "Malbec")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($rb);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential White Bordeaux"
    agenda-group "potential-wines"
    salience 10
    when
        $wb: Wine(wineName == "White bordeaux");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Semillon" || grapeName == "Sauvignon Blanc" || grapeName == "Muscadelle")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($wb);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Red bourgogne"
    agenda-group "potential-wines"
    salience 10
    when
        $rb: Wine(wineName == "Red bourgogne");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Pinot Noir" || grapeName == "Gamay")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($rb);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential White bourgogne"
    agenda-group "potential-wines"
    salience 10
    when
        $wb: Wine(wineName == "White bourgogne");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Chardonnay" || grapeName == "Aligote")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($wb);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Red rhone"
    agenda-group "potential-wines"
    salience 10
    when
        $rr: Wine(wineName == "Red rhone");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Grenache" || grapeName == "Syrah" || grapeName == "Mourvedre")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($rr);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential White rhone"
    agenda-group "potential-wines"
    salience 10
    when
        $wr: Wine(wineName == "White rhone");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Marsanne" || grapeName == "Roussanne" || grapeName == "Viognier" || grapeName == "Clairette"
            || grapeName == "Grenache Blanc" || grapeName == "Bourboulenc")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($wr);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Soave"
    agenda-group "potential-wines"
    salience 10
    when
        $soave: Wine(wineName == "Soave");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Garganega" || grapeName == "Trebbiano" || grapeName == "Chardonnay" || grapeName == "Pinot Blanc")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($soave);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Chianti"
    agenda-group "potential-wines"
    salience 10
    when
        $chianti: Wine(wineName == "Chianti");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Sangiovese" || grapeName == "Cabernet Sauvignon" || grapeName == "Cabernet Franc")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($chianti);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Super tuscan"
    agenda-group "potential-wines"
    salience 10
    when
        $st: Wine(wineName == "Super tuscan");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Merlot" || grapeName == "Cabernet Sauvignon" || grapeName == "Sangiovese"
            || grapeName == "Syrah" || grapeName == "Cabernet Franc")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($st);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Amarone della valpolicella"
    agenda-group "potential-wines"
    salience 10
    when
        $amarone: Wine(wineName == "Amarone della valpolicella");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Corvina" || grapeName == "Molinara" || grapeName == "Rondinella")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($amarone);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Rioja"
    agenda-group "potential-wines"
    salience 10
    when
        $rioja: Wine(wineName == "Rioja");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Tempranillo" || grapeName == "Mazuelo" || grapeName == "Gracino" || grapeName == "Maturana Tinta")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($rioja);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential White rioja"
    agenda-group "potential-wines"
    salience 10
    when
        $wrioja: Wine(wineName == "White rioja");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Viura" || grapeName == "Malvasia" || grapeName == "Verdejo" || grapeName == "Garnacha Blanca")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($wrioja);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Priorat"
    agenda-group "potential-wines"
    salience 10
    when
        $priorat: Wine(wineName == "Priorat");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Grenache" || grapeName == "Syrah" || grapeName == "Carignan" || grapeName == "Cabernet Sauvignon"
            || grapeName == "Merlot")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($priorat);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Meritage"
    agenda-group "potential-wines"
    salience 10
    when
        $meritage: Wine(wineName == "Meritage");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Cabernet Sauvignon" || grapeName == "Merlot" || grapeName == "Cabernet Franc" ||
            grapeName == "Petit Verdot" || grapeName == "Malbec" || grapeName == "Carmenere")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($meritage);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Port"
    agenda-group "potential-wines"
    salience 10
    when
        $port: Wine(wineName == "Port");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Touriga Nacional" || grapeName == "Touriga Franca" || grapeName == "Tinta Roriz" ||
            grapeName == "Tinto Cao" || grapeName == "Tinta Barroca")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($port);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Provence rose"
    agenda-group "potential-wines"
    salience 10
    when
        $rose: Wine(wineName == "Provence rose");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Cinsault" || grapeName == "Grenache" || grapeName == "Syrah" || grapeName == "Rolle")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($rose);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Champagne"
    agenda-group "potential-wines"
    salience 10
    when
        $champ: Wine(wineName == "Champagne");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Chardonnay" || grapeName == "Pinot Meunier" || grapeName == "Pinot Noir")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($champ);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end

rule "Potential Cava"
    agenda-group "potential-wines"
    salience 10
    when
        $cava: Wine(wineName == "Cava");
        $pw: PotentialWinesDTO();
        $gl: GrapeList($grapeList: grapeLists);
        $n: Number(intValue >= 1) from accumulate (
            Grape(grapeName == "Macabeo" || grapeName == "Parellada" || grapeName == "Xarello" || grapeName == "Chardonnay")
            from $grapeList,
            init(int count = 0;),
            action(count += 1;),
            result(count)
        )
    then
        MissingGrapesDTO missingGrapesDTO = new MissingGrapesDTO();
        WineDTO wineDTO = new WineDTO($cava);
        missingGrapesDTO.setWineDTO(wineDTO);
        $pw.getMissingGrapesDTOS().add(missingGrapesDTO);
        insert(wineDTO);
        insert(missingGrapesDTO);
end


rule "Adding all missing grapes for each possible wine"
    agenda-group "potential-wines"
    salience -100
    when
        $wdto: WineDTO($winesGrapes: grapeDTOS)
        $potentialWine: MissingGrapesDTO(wineDTO == $wdto, $missingGrapes: grapeDTOS);
        $gl: GrapeList($usersGrapes: grapeLists);
        $n: Number(intValue >= 0) from accumulate (
            GrapeDTO($grapeName: grapeName, $grapeId: id)
            from $winesGrapes,
            init(int count = 0;),
            action( count += 1;
                    boolean added = false;
                    for(Object grape: $usersGrapes){
                        if(((Grape)grape).getGrapeName().equals($grapeName)){ added = true; }
                    }
                    if(!added){
                        $missingGrapes.add(new GrapeDTO((String)$grapeName, (Long)$grapeId));
                    }
            ),
            result(count)
        )
    then
        System.out.println($n);
end